Repository BitSwap-BiFi/Bitswap-demo, pull requests merged in 2023-10, with the labels that each got.

#23 Add Universal RGB assets allowing swaps
  src/dex/pair.rs
Labels: documentation, enhancement, help wanted, Epic

#27 Add endpoints, APIs for DEX
  .env
Labels: documentation, enhancement, Epic

#29 Add Server and upgrade around RGB Node for DEX
  rgb/Cargo.toml
  server/amm/Cargo.toml
  server/amm/src/api.rs
  server/amm/src/config.rs
  server/amm/src/main.rs
Labels: documentation, enhancement, help wanted, Epic

#28 Add RGB Core v0.10.8
  Cargo.toml
  README.md
  src/contract/asset.rs
Labels: documentation

#34 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#50 Add Docs
  README.md
Labels: documentation, enhancement, lightning network, rgb, dex

#55 Update README
  README.md
Labels: documentation, enhancement, dex

#49 Add BOLT12, LDK upgrade and Universal RGB Assets
  Cargo.toml
  README.md
  src/lightning/ldk.rs
Labels: enhancement, help wanted, Epic, c-priority, rgb, bitcoin

#47 Fix API and typo
  src/dex/api.rs
Labels: bug, documentation, help wanted, c-priority, rgb
