Repository BitSwap-BiFi/Bitswap-demo, pull requests merged in 2023-11, with the labels that each got.

#61 Add AMM manger
  src/dex/functions/main/amm_manager.rs
  src/dex/functions/main/lib.rs
  src/dex/functions/main/utils.rs
Labels: enhancement, Epic, c-priority, lightning network, rgb, bitcoin, dex

#30 Add functions for AMM server
  server/amm/src/api.rs
  server/amm/src/config.rs
  server/amm/src/main.rs
Labels: bug, documentation, enhancement, help wanted, Epic, rgb

#64 Fix BOLT12
  src/lightning/ldk.rs
  src/lightning/swap.rs
Labels: documentation, enhancement, c-priority, lightning network

#26 Add new functions for CLI (Command Line Interface) for DEX
  src/cli/core.rs
Labels: documentation, enhancement, help wanted, Epic, c-priority, lightning network, rgb, dex

#25 Add swap for RGB contracts
  src/contract/asset.rs
Labels: documentation, enhancement, help wanted, Epic, lightning network, rgb

#57 Add RGB Core v0.11.0, Bitcoin protocol and many more upgrades
  Cargo.toml
  README.md
  src/contract/asset.rs
Labels: documentation, Epic, c-priority, rgb, bitcoin, dex

#21 Upgrade algorithm around AMM
  Cargo.toml
  src/dex/algorithm.rs
Labels: documentation, enhancement, help wanted, Epic, c-priority, lightning network, rgb, bitcoin, dex

#75 Add testnet depedencies
  src/testnet.rs
Labels: Epic, c-priority, lightning network, rgb, bitcoin, dex

#80 Remove RGB Node
  rgb/node.rs
Labels: enhancement, lightning network, rgb, bitcoin, dex

#79 Fix AluVM
  src/aluvm/strict.rs
Labels: enhancement, Epic, c-priority, lightning network, rgb, bitcoin, dex

#17 Add new stable version around RGB Wallet
  Cargo.toml
  src/wallet/RGB_wallet.rs
Labels: documentation, enhancement, help wanted, Epic, c-priority, lightning network, rgb, bitcoin, dex

#54 Add doc for development
  doc/development.md
Labels: documentation, Epic, c-priority, dex

#83 Add RGB CLI
  src/cli/core.rs
Labels: documentation, enhancement, Epic, c-priority, lightning network, rgb, bitcoin, dex, rgb-lightning, cli

#87 Add Alpha v1.0.15
  CHANGELOG.md
  Cargo.toml
  README.md
  SECURITY.md
  pacake.json
  package-lock.json
Labels: documentation, bitcoin, dex, bifrost
